language: node_js

# latest stable version
node_js:
  - "stable"

  cache:
  directories:
  - node_modules

  script:
  - cd test-app
  - npm install
  - npm test -- --coverage

  after_script: 
  - npm run coveralls