const type = {
    FETCH: 'FETCH',
    LOADED: 'LOADED',
    YEAR: 'YEAR',
    SORT_BY: 'SORT_BY',
    GENRES: 'GENRES',
    CAST: 'CAST',
    CAST_VALUE: 'CAST_VALUE',
    LOADED_CAST: 'LOADED_CAST',
    KEYWORDS: 'KEYWORDS',
    KEYWORDS_VALUE: 'KEYWORDS_VALUE',
    LOADED_KEYWORDS: 'LOADED_KEYWORDS',
    PAGE: 'PAGE',
    NEXT_PAGE: 'NEXT_PAGE',
    PREV_PAGE: 'PREV_PAGE',
    LAST_PAGE: 'LAST_PAGE',
    ERRORS: 'ERRORS'
}

export default type